#!/bin/sh
#
# Lint everything under .github/: GitHub Actions workflows
# (actionlint for syntax/structure, zizmor for security audits),
# YAML files (yamllint), and CODEOWNERS (codeowners-validator).
#
# actionlint and zizmor are complementary: actionlint checks
# expression validity, runner labels, event triggers, and pipes
# `run:` blocks through shellcheck; zizmor audits for security
# issues (excessive permissions, credential persistence, template
# injection, …) that actionlint doesn't cover.
#
# Tools required on PATH:
#   - actionlint           https://github.com/rhysd/actionlint
#   - zizmor               https://github.com/zizmorcore/zizmor
#   - yamllint             https://github.com/adrienverge/yamllint
#   - codeowners-validator https://github.com/mszostok/codeowners-validator
# Consult .devcontainer/Dockerfile for the pinned versions.
#
# yamllint config lives in .yamllint at the repo root.
#
# CODEOWNERS validation runs syntax, duppatterns, notowned, and
# avoid-shadowing. None touch the GitHub API, so no token
# is required. The optional `owners` check (verify each @handle
# resolves to a real user with repo access) is not run here because
# it requires a Personal Access Token with the `read:org` scope,
# which the default GITHUB_TOKEN does not grant. To run it manually:
#   GITHUB_ACCESS_TOKEN=<PAT> REPOSITORY_PATH=. CHECKS=owners \
#     codeowners-validator
#
# POSIX sh only.

set -eu

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH='' cd -- "$SCRIPT_DIR/../../.." && pwd)

cd "$REPO_ROOT"

banner() {
  printf '\n----- %s -----\n' "$1"
}

# Run every check even if an earlier one fails; collect names of any
# failures and report them in a summary at the end. The `|| ...`
# pattern locally suppresses `set -e` for the check invocation.
failures=""

# The dist-generated release workflow (.github/workflows/release.yml) is
# owned and regenerated by `dist generate`: it pins official actions/* to
# major-version tags and quotes its shell on dist's terms, and hand-edits
# would be clobbered on the next regeneration. Its validity and release plan
# are covered by `dist plan` / `dist generate --check` instead. Exclude it
# from our actionlint/zizmor gate rather than fight the generator; every
# other workflow is ours and stays fully gated. (yamllint still covers it —
# its config disables line-length, the rule dist's long generated lines
# would otherwise trip.)
set --
for wf in .github/workflows/*.yml .github/workflows/*.yaml; do
  [ -e "$wf" ] || continue
  case "$wf" in
    */release.yml) continue ;;
  esac
  set -- "$@" "$wf"
done

banner actionlint
actionlint "$@" || failures="$failures actionlint"

banner zizmor
# Audit only the workflows we own. zizmor's default exit code is
# non-zero when any finding is reported; that's the behavior we
# want — every finding fails CI until it's either fixed or
# explicitly suppressed in a zizmor config.
zizmor "$@" || failures="$failures zizmor"

banner yamllint
yamllint .github || failures="$failures yamllint"

banner codeowners-validator
# codeowners-validator's `notowned` experimental check refuses to run
# on a dirty working tree. Skip it when local state is dirty so the
# script stays runnable mid-edit; CI always sees a clean checkout.
# The `files` check is intentionally omitted: in codeowners-validator
# 0.7.4 it can report catch-all glob patterns as matching no files even
# when `notowned` proves the repository is fully covered.
EXPERIMENTAL_CHECKS="notowned,avoid-shadowing"
if [ -n "$(git status --porcelain)" ]; then
  EXPERIMENTAL_CHECKS="avoid-shadowing"
  echo "note: skipping codeowners-validator 'notowned' check (dirty git tree); commit or stash to enable." >&2
  REPOSITORY_PATH="$REPO_ROOT" \
    CHECKS="duppatterns,syntax" \
    EXPERIMENTAL_CHECKS="$EXPERIMENTAL_CHECKS" \
    codeowners-validator || failures="$failures codeowners-validator"
else
  # The notowned checker resets the repository it inspects. Confine that
  # destructive traversal to a detached snapshot so parallel CI jobs can keep
  # reading the active checkout.
  CHECKS="duppatterns,syntax" \
    EXPERIMENTAL_CHECKS="$EXPERIMENTAL_CHECKS" \
    sh "$SCRIPT_DIR/lib/codeowners-validator-isolated.sh" \
      "$REPO_ROOT" codeowners-validator || failures="$failures codeowners-validator"
fi

if [ -n "$failures" ]; then
  banner summary
  printf 'FAILED:%s\n' "$failures" >&2
  exit 1
fi
