//! Kio' → Python lowering.

use crate::ast::Routed;

const RUNTIME: &str = include_str!("runtime.py");

#[derive(Debug)]
pub struct EmitError {
    pub message: String,
}

impl EmitError {
    fn internal(detail: impl Into<String>) -> Self {
        Self {
            message: detail.into(),
        }
    }
}

/// Lower a typed (post-recovery) Kio package to a single Python module.
/// `namespace` is the effective module stem (`<namespace>.py`), from which
/// the public factory's value brand derives. The default namespace derives
/// from the package name via `default_python_namespace`; the `namespace`
/// build-block key supplies an explicit override.
pub fn lower_package_to_module(
    package: &crate::pass::resolve::Package<Routed>,
    namespace: &str,
) -> Result<String, EmitError> {
    lower_package_to_module_with_signature(package, namespace, None)
}

/// Lower a package with sealed signature history available to shared boundary
/// preparation. Python emits only live declarations; history-only sites and
/// their dependencies have no runtime representation or execution path.
pub fn lower_package_to_module_with_signature(
    package: &crate::pass::resolve::Package<Routed>,
    namespace: &str,
    sig: Option<&(u32, crate::sig::ReplayedInterface)>,
) -> Result<String, EmitError> {
    let ir = crate::backends::serialized_runtime_ir::python_package_ir(
        package,
        sig.map(|(_, replayed)| replayed),
    )
    .map_err(EmitError::internal)?;
    let ir_json = serde_json::to_string(&ir)
        .map_err(|e| EmitError::internal(format!("cannot encode Python IR: {e}")))?;

    let mut out = String::new();
    out.push_str("# Generated by kio - do not edit by hand.\n");
    out.push_str("import json\n\n");
    out.push_str(RUNTIME);
    out.push_str("\n\n_KIO_IR = json.loads(");
    out.push_str(&python_chunked_string_literal(&ir_json));
    out.push_str(")\n");
    out.push_str("_KIO_PACKAGE = _CompiledPackage(_KIO_IR)\n\n");
    out.push_str("_KIO_PACKAGE.install_declarations(globals())\n\n");
    out.push_str(&format!(
        "def create_{}(host=None):\n",
        crate::backends::namespace::value_brand(namespace)
    ));
    out.push_str("    return _KIO_PACKAGE.create(host)\n");
    Ok(out)
}

fn python_string_literal(s: &str) -> String {
    let mut out = String::from("'");
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\x{:02x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('\'');
    out
}

fn python_chunked_string_literal(s: &str) -> String {
    const CHUNK_CHARS: usize = 1000;
    let mut out = String::from("(\n");
    let mut chunk = String::new();
    for ch in s.chars() {
        chunk.push(ch);
        if chunk.chars().count() >= CHUNK_CHARS {
            out.push_str("    ");
            out.push_str(&python_string_literal(&chunk));
            out.push('\n');
            chunk.clear();
        }
    }
    if !chunk.is_empty() {
        out.push_str("    ");
        out.push_str(&python_string_literal(&chunk));
        out.push('\n');
    }
    out.push(')');
    out
}
