//! Go backend — runtime-support library.
//!
//! The Go backend ships a fixed `kio_runtime.go` file in every emitted
//! package directory. The file holds the package-agnostic helpers the
//! per-variant emit calls into instead of inlining: the canonical `Unit`
//! value and structural carrier peels. See [`crate::backends`](super::super)
//! § Runtime-support library convention for the framework-level
//! rationale.
//!
//! Go's body is **erased** — every value flows as `interface{}` /
//! `[]any` (the JS dynamic body's shape, on a statically-typed host).
//! `interface{}` is a genuine dynamic universal carrier, so a
//! higher-kinded carrier (`F(A)` inside a Functor / Monad dictionary)
//! needs **no carrier-walk**: the concrete-use-site carrier and the
//! dictionary-internal binder-erased carrier share one uniform `[]any`
//! runtime rep, and the host never sees the body's types. Go, Rust, and
//! Swift all erase their bodies to a dynamic universal carrier this way;
//! a carrier-walk is load-bearing only for a **native-HKT** host
//! (Haskell) that threads a typed carrier. See
//! [`ai/topics/emit.md`](../../../../ai/topics/emit.md) § Runtime model.
//!
//! The content lives here as canonical `&str` constants so it ships
//! with the kio-rs binary; [`runtime_support_content`] binds the
//! package-namespace line (the `package <ns>` clause) and everything
//! below it is byte-identical across packages. The build-side
//! dispatcher writes it under `kio_runtime.go` alongside the package's
//! `pkg.go`, `host.go`, `shapes.go`, `ffi.go`. The file is **not
//! user-modifiable** — the emitter overwrites it on every build.

/// The relative path the build-side dispatcher writes the runtime file
/// to. Mirrored in [`super::profile`]'s
/// [`super::super::RuntimeSupport::EmbeddedFile::path`] field.
///
/// **Not** underscore-prefixed (unlike Rust's `__kio_runtime.rs`): the
/// Go toolchain ignores any source file whose name begins with `_` or
/// `.` (it treats them as non-build files), so `__kio_runtime.go` would
/// silently drop out of `go build`. `kio_runtime.go` keeps the
/// internal-file intent (the `kio_` prefix) without tripping that rule.
pub const RUNTIME_SUPPORT_FILE_PATH: &str = "kio_runtime.go";

/// The canonical content of `kio_runtime.go` for a package whose
/// emitted `package` clause is `ns`. The clause is the only
/// namespace binding; everything below it is byte-identical across
/// packages, re-emitted on every build.
///
/// What lives below the binding:
///
/// - `Unit` — Go has no unit value; `struct{}` is the canonical empty.
///   Kio `()` lowers to `Unit{}`.
/// - `kioProductSlots` / `kioProductSlot` and `kioSumPayload` /
///   `kioSumInject` name the erased structural carrier walks.
///
/// Go's erased body carries higher-kinded payloads in the uniform
/// `[]any` rep, so it needs **no** runtime brand value or carrier-walk.
/// The file is package-level documented as generated; gofmt-stable.
pub fn runtime_support_content(ns: &str) -> String {
    format!("{RUNTIME_SUPPORT_HEADER}package {ns}\n{RUNTIME_SUPPORT_BODY}")
}

const RUNTIME_SUPPORT_HEADER: &str = r#"// Generated by kio — do not edit by hand.
//
// Runtime-support library for the Go backend. The kio emitter writes
// this file alongside pkg.go / host.go / shapes.go / ffi.go in
// every emitted package; it holds the package-agnostic helpers the
// package's emit calls into. The file is rewritten on every
// `kio build` — host-side edits will not survive.

"#;

const RUNTIME_SUPPORT_BODY: &str = r#"
// Unit is the Go representation of Kio's `()` (unit). Go has no unit
// value, so `struct{}` stands in; every `()` lowers to `Unit{}`.
type Unit = struct{}

func kioProductSlots(v any, arity int) []any {
	slots := make([]any, 0, arity)
	cur := v
	for i := 0; i < arity; i++ {
		if i+1 == arity {
			slots = append(slots, cur)
		} else {
			pair := cur.([]any)
			slots = append(slots, pair[0])
			cur = pair[1]
		}
	}
	return slots
}

func kioProductSlot(v any, index int, arity int) any {
	if index < 0 || index >= arity {
		panic("kio erased body: invalid product slot")
	}
	cur := v
	for i := 0; i < arity; i++ {
		if i+1 == arity {
			return cur
		}
		pair := cur.([]any)
		if i == index {
			return pair[0]
		}
		cur = pair[1]
	}
	panic("kio erased body: invalid product slot")
}

func kioSumPayload(v any, variants int) (int, any) {
	if variants <= 0 {
		panic("kio erased body: invalid sum arity")
	}
	cur := v
	for variant := 0; variant < variants-1; variant++ {
		pair := cur.([]any)
		if pair[0].(int) == 0 {
			return variant, pair[1]
		}
		cur = pair[1]
	}
	return variants - 1, cur
}

func kioSumInject(payload any, variant int, variants int) any {
	if variants <= 0 || variant < 0 || variant >= variants {
		panic("kio erased body: invalid sum variant")
	}
	acc := payload
	if variant+1 < variants {
		acc = []any{int(0), payload}
	}
	for i := 0; i < variant; i++ {
		acc = []any{int(1), acc}
	}
	return acc
}
"#;
