//! Swift backend — runtime-support library.
//!
//! The Swift backend ships a fixed `kio_runtime.swift` file in every
//! emitted package directory. The file holds the package-agnostic helpers
//! the per-variant emit calls into instead of inlining: the canonical
//! `Unit` value and structural carrier peels. See [`crate::backends`](super::super)
//! § Runtime-support library convention for the framework-level
//! rationale.
//!
//! Swift's body is **erased** — every value flows as `Any` / `[Any]`
//! (the JS dynamic body's shape, on a statically-typed host). `Any` is a
//! genuine dynamic universal carrier, so a higher-kinded carrier (`F(A)`
//! inside a Functor / Monad dictionary) needs **no carrier-walk**: the
//! concrete-use-site carrier and the dictionary-internal binder-erased
//! carrier share one uniform `[Any]` runtime rep, and the host never sees
//! the body's types. Go, Rust, and Swift all erase their bodies to a
//! dynamic universal carrier this way; a carrier-walk is load-bearing
//! only for a **native-HKT** host (Haskell) that threads a typed carrier.
//! See [`ai/topics/emit.md`](../../../../ai/topics/emit.md)
//! § Runtime model.
//!
//! The content lives here as a `&str` constant so it ships with the
//! kio-rs binary. The build-side dispatcher writes it under
//! `kio_runtime.swift` alongside the package's `pkg.swift`, `host.swift`,
//! `shapes.swift`, `ffi.swift`. The file is **not user-modifiable** — the
//! emitter overwrites it on every build.
//!
//! Unlike Go's runtime file — which binds a `package <ns>` clause per
//! package — a Swift source carries **no** module declaration (the module
//! name is imposed at compile time via `-module-name`), and this file
//! references no branded or module name. Its content is therefore
//! **fixed**: byte-identical across every emitted package (a plain `&str`
//! constant, not a `runtime_support_content(ns)` function), the strongest
//! form of the framework's canonical-content property
//! ([`crate::backends`] § Runtime-support library).

/// The relative path the build-side dispatcher writes the runtime file
/// to. Mirrored in [`super::profile`]'s
/// [`super::super::RuntimeSupport::EmbeddedFile::path`] field.
pub const RUNTIME_SUPPORT_FILE_PATH: &str = "kio_runtime.swift";

/// The canonical content of `kio_runtime.swift`. Held as a `&str`
/// constant so the emitter ships it verbatim; re-emitted on every build.
///
/// What lives here (package-agnostic, the same bytes in every emitted
/// package):
///
/// - `KioUnit` — Swift's `()` / `Void` is awkward to carry nominally
///   through the erased `Any` body and to match at the FFI boundary; a
///   dedicated empty `struct KioUnit` is the canonical empty. Kio `()`
///   lowers to `KioUnit()`. It is `public` because `()` can cross the
///   FFI boundary, and the emitted package is a Swift module the host
///   imports (the Swift analogue of Go's exported `Unit`).
/// - `kioProductNest` / `kioProductSlots` / `kioProductSlot` and
///   `kioSumPayload` / `kioSumInject` name the erased structural carrier
///   construction and walks.
///
/// Swift's erased body carries higher-kinded payloads in the uniform
/// `[Any]` rep, so it needs **no** runtime brand value or carrier-walk.
pub const RUNTIME_SUPPORT_FILE_CONTENT: &str = r#"// Generated by kio — do not edit by hand.
//
// Runtime-support library for the Swift backend. The kio emitter writes
// this file alongside pkg.swift / host.swift / shapes.swift / ffi.swift
// in every emitted package; it holds the package-agnostic helpers the
// package's emit calls into. The file is rewritten on every
// `kio build` — host-side edits will not survive.

// KioUnit is the Swift representation of Kio's `()` (unit). Swift's `()`
// is awkward to carry nominally through the erased `Any` body, so an empty
// struct stands in; every `()` lowers to `KioUnit()`. The name is
// `Kio`-prefixed (reserved) so it cannot be shadowed by a user type named
// `Unit` exported as a namespace member — Swift member lookup would
// resolve a bare module-level `Unit` to that property. It is `public` so
// it can cross the FFI boundary into the importing host module.
public struct KioUnit: Equatable {
    public init() {}
}

func kioProductNest(_ slots: [Any]) -> Any {
    precondition(!slots.isEmpty, "kio erased body: empty product")
    var acc = slots[slots.count - 1]
    if slots.count > 1 {
        for index in stride(from: slots.count - 2, through: 0, by: -1) {
            acc = [slots[index], acc] as [Any]
        }
    }
    return acc
}

func kioProductSlots(_ v: Any, _ arity: Int) -> [Any] {
    var slots: [Any] = []
    slots.reserveCapacity(arity)
    var cur = v
    for i in 0..<arity {
        if i + 1 == arity {
            slots.append(cur)
        } else {
            let pair = cur as! [Any]
            slots.append(pair[0])
            cur = pair[1]
        }
    }
    return slots
}

func kioProductSlot(_ v: Any, _ index: Int, _ arity: Int) -> Any {
    precondition(index >= 0 && index < arity, "kio erased body: invalid product slot")
    var cur = v
    for i in 0..<arity {
        if i + 1 == arity {
            return cur
        }
        let pair = cur as! [Any]
        if i == index {
            return pair[0]
        }
        cur = pair[1]
    }
    fatalError("kio erased body: invalid product slot")
}

func kioSumPayload(_ v: Any, _ variants: Int) -> (Int, Any) {
    precondition(variants > 0, "kio erased body: invalid sum arity")
    var cur = v
    for variant in 0..<(variants - 1) {
        let pair = cur as! [Any]
        if pair[0] as! Int == 0 {
            return (variant, pair[1])
        }
        cur = pair[1]
    }
    return (variants - 1, cur)
}

func kioSumInject(_ payload: Any, _ variant: Int, _ variants: Int) -> Any {
    precondition(
        variants > 0 && variant >= 0 && variant < variants,
        "kio erased body: invalid sum variant"
    )
    var acc = payload
    if variant + 1 < variants {
        acc = [0, payload] as [Any]
    }
    for _ in 0..<variant {
        acc = [1, acc] as [Any]
    }
    return acc
}
"#;
