//! Rust backend — runtime-support library.
//!
//! The Rust backend ships a fixed `src/__kio_runtime.rs` file in
//! every emitted Cargo crate. The file holds the closure-wrap and
//! erase / recover helpers the per-variant emit calls into instead of
//! inlining the bodies. See
//! [`crate::backends`](super::super) § Runtime-support library
//! convention for the framework-level rationale.
//!
//! The Rust body is **erased**. In the default representation every value
//! flows as `Rc<dyn Any>` (the open universal, Rust's analog of Go's
//! `interface{}` / Swift's `Any`); the thread-safe option transforms the
//! emitted runtime to `Arc<dyn Any + Send + Sync>`. Scalars box through
//! [`as_any`], products / sums ride the erased nested-binary shape, closures
//! use the corresponding reference-counted erased callable, and an abstract
//! higher-kinded application is an ordinary erased value. The host never sees
//! the body's types; the public marker/facade layer reconstitutes the exact
//! structural, callable, application, rank-N, and nominal boundary values.
//!
//! The content lives here as a `&str` constant so it ships with the
//! kio-rs binary. The build-side dispatcher
//! ([`crate::cmd::build::write_rust_crate`]) writes it under
//! `src/__kio_runtime.rs` alongside `lib.rs`, `host.rs`,
//! `shapes.rs`. The file is **not user-modifiable** — the emitter
//! overwrites it on every build.

/// The relative path the build-side dispatcher writes the runtime
/// file to. Mirrored in [`super::profile`]'s
/// [`super::super::RuntimeSupport::EmbeddedFile::path`] field.
pub const RUNTIME_SUPPORT_FILE_PATH: &str = "src/__kio_runtime.rs";

/// The Rust module name the emitted code references the runtime
/// file's items as. `lib.rs` declares `pub mod __kio_runtime;` so
/// internal call sites read `crate::__kio_runtime::as_any(...)`,
/// `crate::__kio_runtime::from_any(...)`, etc.
pub const RUNTIME_SUPPORT_MODULE: &str = "__kio_runtime";

/// The canonical content of `src/__kio_runtime.rs`. Held as a
/// `&str` constant so the emitter ships it verbatim. The file is
/// re-emitted on every build — kio is the source of truth for its
/// content.
///
/// Helpers exposed:
///
/// - `as_any` — box any `'static` value behind `Rc<dyn Any>` (the
///   erased body's universal value). `from_any` recovers it.
/// - `product_slots` / `product_slot` — peel the erased right-nested
///   product carrier once and reuse the flat slots.
/// - `sum_payload` / `sum_inject` — convert between a flat variant
///   index and the erased right-nested tagged sum carrier.
///
/// The file is `#[allow(dead_code)]` because a given package emit
/// may not exercise every helper — a value-free package uses no
/// `as_any`. Suppressing the lint at the file level keeps emitted
/// crates warning-free without per-package pruning.
pub const RUNTIME_SUPPORT_FILE_CONTENT: &str = r#"// Generated by kio — do not edit by hand.
//
// Runtime-support library for the Rust backend. The kio emitter
// writes this file alongside `lib.rs` / `host.rs` / `shapes.rs`
// in every emitted crate; it holds the erase / recover helpers the
// package's emit calls into. The file is rewritten on every
// `kio build` — host-side edits will not survive.

#![allow(dead_code)]

use std::any::Any;
use std::rc::Rc;

/// Opaque canonical value stored by generated public facade carriers.
///
/// Hosts may clone and retain this token, including inside a
/// declaration-owned parameterized-host storage type. Public marker and
/// `KioValue` APIs move these opaque tokens across typed facade boundaries;
/// the erased `Any` value and its downcast operations remain private.
#[derive(Clone)]
pub struct KioStoredValue(Rc<dyn Any>);

impl KioStoredValue {
    pub(crate) fn from_raw(value: Rc<dyn Any>) -> Self {
        Self(value)
    }

    pub(crate) fn raw(&self) -> Rc<dyn Any> {
        self.0.clone()
    }

    pub(crate) fn into_raw(self) -> Rc<dyn Any> {
        self.0
    }
}

/// Box a `'static` value behind `Rc<dyn Any>` — the erased body's
/// universal value. Every value the body computes is boxed here:
/// scalars, the nested-binary product / sum cells, and the boxed
/// closures. [`from_any`] recovers the concrete value at a narrowing
/// site.
pub(crate) fn as_any<T: 'static>(v: T) -> Rc<dyn Any> {
    Rc::new(v)
}

/// Recover a concrete `'static` value previously erased with
/// [`as_any`]. The inverse of `as_any`: downcasts the `Rc<dyn Any>`
/// back to `T` and clones it out.
///
/// The whole body computes over `Rc<dyn Any>`, so every narrowing —
/// applying an erased closure, peeling a product / sum slot, handing
/// an erased value to a typed host slot — recovers its concrete type
/// here. A well-typed program drives a consistent type to each
/// recovery site, so the downcast cannot fail unless generated code violated
/// its representation invariant or a host deliberately relabelled malformed
/// `KioStoredValue` data inside declaration-owned storage. Either case is a
/// boundary-contract violation, not a recoverable Kio program error.
pub(crate) fn from_any<T: Clone + 'static>(v: Rc<dyn Any>) -> T {
    (*v
        .downcast::<T>()
        .expect(
            "kio erased body: from_any downcast failed — generated representation or host storage contract violated",
        ))
    .clone()
}

pub(crate) fn product_slots(v: Rc<dyn Any>, arity: usize) -> Vec<Rc<dyn Any>> {
    let mut slots = Vec::with_capacity(arity);
    let mut cur = v;
    for i in 0..arity {
        if i + 1 == arity {
            slots.push(cur);
            break;
        }
        let pair: (Rc<dyn Any>, Rc<dyn Any>) = from_any(cur);
        slots.push(pair.0);
        cur = pair.1;
    }
    slots
}

pub(crate) fn product_slot(v: Rc<dyn Any>, index: usize, arity: usize) -> Rc<dyn Any> {
    assert!(index < arity, "kio erased body: invalid product slot");
    let mut cur = v;
    for i in 0..arity {
        if i + 1 == arity {
            return cur;
        }
        let pair: (Rc<dyn Any>, Rc<dyn Any>) = from_any(cur);
        if i == index {
            return pair.0;
        }
        cur = pair.1;
    }
    unreachable!("kio erased body: invalid product slot")
}

pub(crate) fn sum_payload(v: Rc<dyn Any>, variants: usize) -> (usize, Rc<dyn Any>) {
    assert!(variants > 0, "kio erased body: invalid sum arity");
    let mut cur = v;
    for variant in 0..variants.saturating_sub(1) {
        let pair: (usize, Rc<dyn Any>) = from_any(cur);
        if pair.0 == 0 {
            return (variant, pair.1);
        }
        cur = pair.1;
    }
    (variants.saturating_sub(1), cur)
}

pub(crate) fn sum_inject(payload: Rc<dyn Any>, variant: usize, variants: usize) -> Rc<dyn Any> {
    assert!(
        variants > 0 && variant < variants,
        "kio erased body: invalid sum variant"
    );
    let mut acc = if variant + 1 < variants {
        as_any((0usize, payload))
    } else {
        payload
    };
    for _ in 0..variant {
        acc = as_any((1usize, acc));
    }
    acc
}

"#;
